### ISSUE TITLE
landing-page: style to fit components

### ISSUE THREAD

**Issue by raymondmay95** [alex-pezzati/sonic-fog#19]
For a logged out user:
 - There are three components:
  - [x] Top Songs
  - [x] Genres
  - [ ]  Featured

For a logged in user:
 - There are at least five components:
  - [ ] Top Songs
  - [ ]  Genres
  - [ ]  Featured
  - [ ]  Uploaded
  - [ ]  Personal

**Comment by alex-pezzati** [comment]
we concluded to look at this later in the week
